version: '2'
services:
  db:
    build: ./db
    volumes:
      - ./db/pgdata:/pgdata
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=docker
      - POSTGRES_PASSWORD=docker
      - PGDATA=/pgdata
    command: ["postgres", "-c", "log_statement=all"]

#  api:
#    build:
#      context: ./
#      args:
#        app_env: ${APP_ENV}
#    volumes:
#      - ./:/api
#    ports:
#      - "8080:8080"
#    links:
#      - db

  frontend:
    build:
      context: ./frontend
      args:
        app_env: ${APP_ENV}
    volumes:
      - ./frontend/src:/frontend/src
    ports:
      - "80:3000"
